services:
  app:
    image: node:22
    container_name: adonis_js_node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - adonis-node-volume:/usr/src/app/node_modules
    ports:
      - "3333:3333"
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=my_database
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  adonis-node-volume:
